database:
  name: ""
  uri: ""

  auto-save: 5 #how many minutes should it auto save

drop-time: 5 #in seconds

#not coded, need vault api
currency-type: PLUGIN #can be VAULT or PLUGIN (PLUGIN makes currency stored in this plugin)

item-layouts:
  generators:
    name: "<name><reset> <white>Generator"
    lore:
      - ""
      - "Generators spawn drops that"
      - "sell for money."
      - ""
      - "Sell Price: <sell>"
      - "Upgrade Price: <upgrade>"
      - ""
      - "<green>Place down"
  drops:
    name: "<name><reset> <white>Drop"
    lore:
      - ""
      - "Sell drops to earn money."
      - ""
      - "Sell Price: <sell>"
      - ""
      - "<green>Right click to /sell"
messages:
  sell:
    - "<dark_gray><underlined>                     "
    - "<green><bold>SELL REPORT"
    - ""
    - "You sold <green><amount><reset> drops for <green>$<earned><reset> cash!"
    - "<dark_gray><underlined>                     "
  sell-empty: "<red>You have nothing to sell."
  pickup: "<green>You picked up a generator!"
  placed: "<green>You picked up a generator!"